// JSZip is lazy loaded to reduce initial bundle size

const getFontFamily = (family, category) => {
  const fallback = category.toLowerCase().includes('serif')
    ? 'serif'
    : 'sans-serif'
  return `"${family}", ${fallback}`
}

/**
 * Generate CSS Variables Export
 * Creates CSS custom properties (variables) for typography system
 *
 * @param {Object} config - Typography configuration object
 * @returns {string} CSS code with custom properties
 *
 * @example
 * // Usage in CSS:
 * .heading {
 *   font-family: var(--font-heading);
 *   font-weight: var(--heading-weight);
 *   letter-spacing: var(--heading-tracking);
 *   line-height: var(--heading-leading);
 * }
 *
 * // Usage in HTML:
 * <h1 style="font-family: var(--font-heading);">Title</h1>
 *
 * // Responsive typography example:
 * @media (max-width: 768px) {
 *   .heading {
 *     font-size: clamp(1.5rem, 4vw, 2.5rem);
 *     font-family: var(--font-heading);
 *   }
 * }
 */
export const generateCSSExport = config => {
  const getRoleConfig = role => config[role]?.all || {}

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  // Collect all unique fonts with their weights for Google Fonts URL
  const fontMap = new Map()

  // Helper to add font with weight
  const addFont = (family, weight) => {
    if (!family) return
    if (!fontMap.has(family)) {
      fontMap.set(family, new Set())
    }
    fontMap.get(family).add(weight)
  }

  // Add base fonts
  addFont(headingConfig.family, headingConfig.weight)
  addFont(bodyConfig.family, bodyConfig.weight)
  addFont(uiConfig.family, uiConfig.weight)

  // Add element-specific fonts
  Object.values(config.headings || {}).forEach(elemConfig => {
    if (elemConfig?.family) addFont(elemConfig.family, elemConfig.weight)
  })
  Object.values(config.body || {}).forEach(elemConfig => {
    if (elemConfig?.family) addFont(elemConfig.family, elemConfig.weight)
  })
  Object.values(config.ui || {}).forEach(elemConfig => {
    if (elemConfig?.family) addFont(elemConfig.family, elemConfig.weight)
  })

  // Build Google Fonts URL with weights
  const googleFontsUrl = Array.from(fontMap.entries())
    .map(([family, weights]) => {
      const familyName = family.replace(/\s+/g, '+')
      const weightList = Array.from(weights).join(';')
      return `family=${familyName}:wght@${weightList}`
    })
    .join('&')

  let css = `/**
 * Typography System - CSS Variables
 * Generated by TypePalette
 * 
 * This file contains CSS custom properties for your typography system.
 * Import this file in your main stylesheet or link it in your HTML.
 * 
 * Usage:
 *   1. Link this file: <link rel="stylesheet" href="css-variables.css">
 *   2. Use variables: font-family: var(--font-heading);
 * 
 * Accessibility Note:
 *   - Ensure sufficient contrast ratios (WCAG AA: 4.5:1 for body, 3:1 for headings)
 *   - Test with screen readers to verify font choices work well
 *   - Consider user font size preferences (respect browser zoom)
 * 
 * Dark Mode Support:
 *   Use CSS custom properties with color-scheme or prefers-color-scheme:
 *   @media (prefers-color-scheme: dark) {
 *     :root {
 *       --text-color: #ffffff;
 *     }
 *   }
 */

/* Uncomment the line below to import Google Fonts via @import */
/* @import url('https://fonts.googleapis.com/css2?${googleFontsUrl}&display=swap'); */

:root {
  /* Typography System - Base Variables */
  /* Heading Typography */
  --font-heading: ${getFontFamily(headingConfig.family, headingConfig.category)};
  --heading-weight: ${headingConfig.weight};
  --heading-tracking: ${headingConfig.tracking}em;
  --heading-leading: ${headingConfig.leading};
  --heading-transform: ${headingConfig.transform};

  /* Body Typography */
  --font-body: ${getFontFamily(bodyConfig.family, bodyConfig.category)};
  --body-weight: ${bodyConfig.weight};
  --body-tracking: ${bodyConfig.tracking}em;
  --body-leading: ${bodyConfig.leading};
  --body-transform: ${bodyConfig.transform};

  /* UI Typography */
  --font-ui: ${getFontFamily(uiConfig.family, uiConfig.category)};
  --ui-weight: ${uiConfig.weight};
  --ui-tracking: ${uiConfig.tracking}em;
  --ui-leading: ${uiConfig.leading};
  --ui-transform: ${uiConfig.transform};`

  // Add element-specific CSS variables for headings
  Object.keys(config.headings || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.headings[element]
      css += `
  --font-heading-${element}: ${getFontFamily(elemConfig.family, elemConfig.category)};
  --heading-${element}-weight: ${elemConfig.weight};
  --heading-${element}-tracking: ${elemConfig.tracking}em;
  --heading-${element}-leading: ${elemConfig.leading};
  --heading-${element}-transform: ${elemConfig.transform};`
    }
  })

  // Add element-specific CSS variables for body
  Object.keys(config.body || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.body[element]
      css += `
  --font-body-${element}: ${getFontFamily(elemConfig.family, elemConfig.category)};
  --body-${element}-weight: ${elemConfig.weight};
  --body-${element}-tracking: ${elemConfig.tracking}em;
  --body-${element}-leading: ${elemConfig.leading};
  --body-${element}-transform: ${elemConfig.transform};`
    }
  })

  // Add element-specific CSS variables for ui
  Object.keys(config.ui || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.ui[element]
      css += `
  --font-ui-${element}: ${getFontFamily(elemConfig.family, elemConfig.category)};
  --ui-${element}-weight: ${elemConfig.weight};
  --ui-${element}-tracking: ${elemConfig.tracking}em;
  --ui-${element}-leading: ${elemConfig.leading};
  --ui-${element}-transform: ${elemConfig.transform};`
    }
  })

  css += `
}`

  return css.trim()
}

/**
 * Generate Basic Tailwind v4 Theme Export
 * Creates minimal Tailwind v4 @theme configuration
 *
 * @param {Object} config - Typography configuration object
 * @returns {string} Tailwind v4 theme CSS
 *
 * @example
 * // Add this to your CSS file or Tailwind config
 * // Usage in HTML:
 * <h1 class="font-display">Heading</h1>
 * <p class="font-sans">Body text</p>
 * <button class="font-ui">Button</button>
 *
 * // With responsive utilities:
 * <h1 class="font-display text-2xl md:text-4xl lg:text-5xl">Responsive Heading</h1>
 */
export const generateTailwindExport = config => {
  const getRoleConfig = role => config[role]?.all || {}

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  return `/**
 * Tailwind v4 Theme Configuration - Basic
 * Generated by TypePalette
 * 
 * Add this to your main CSS file or import it in your Tailwind config.
 * This is a minimal configuration for Tailwind v4.
 * 
 * Installation:
 *   1. Ensure you're using Tailwind CSS v4+
 *   2. Add this code to your CSS file
 *   3. Use utility classes: font-display, font-sans, font-ui
 * 
 * For a more comprehensive configuration, see tailwind-comprehensive.css
 */

@theme {
  /* Font Family Utilities */
  --font-display: ${getFontFamily(headingConfig.family, headingConfig.category)};
  --font-sans: ${getFontFamily(bodyConfig.family, bodyConfig.category)};
  --font-ui: ${getFontFamily(uiConfig.family, uiConfig.category)};
}
`.trim()
}

/**
 * Generate Comprehensive Tailwind v4 Configuration
 * Creates a full-featured Tailwind v4 theme with all typography variables and utility classes
 *
 * @param {Object} config - Typography configuration object
 * @returns {string} Comprehensive Tailwind v4 configuration CSS
 *
 * @example
 * // Usage with utility classes:
 * <h1 class="text-heading-xl">Extra Large Heading</h1>
 * <p class="text-body-base">Base body text</p>
 * <span class="text-ui">UI element</span>
 *
 * // Element-specific classes:
 * <p class="text-body-paragraph">Paragraph text</p>
 * <strong class="text-body-strong">Bold text</strong>
 * <em class="text-body-emphasis">Italic text</em>
 *
 * // Responsive typography:
 * <h1 class="text-heading-xl md:text-heading-2xl lg:text-heading-3xl">
 *   Responsive heading
 * </h1>
 */
export const generateComprehensiveTailwindConfig = config => {
  const getRoleConfig = role => config[role]?.all || {}

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  const headingFamily = getFontFamily(
    headingConfig.family,
    headingConfig.category
  )
  const bodyFamily = getFontFamily(bodyConfig.family, bodyConfig.category)
  const uiFamily = getFontFamily(uiConfig.family, uiConfig.category)

  let tailwindConfig = `/**
 * Tailwind v4 Comprehensive Theme Configuration
 * Generated by TypePalette
 * 
 * This file provides a complete typography system for Tailwind v4.
 * It includes theme variables and custom utility classes.
 * 
 * Installation:
 *   1. Ensure Tailwind CSS v4+ is installed
 *   2. Add this file to your CSS or import it
 *   3. Use the provided utility classes
 * 
 * Features:
 *   - Theme variables for all typography properties
 *   - Custom utility classes for headings and body text
 *   - Element-specific typography classes
 *   - Responsive typography support
 * 
 * Accessibility:
 *   - Maintains proper heading hierarchy
 *   - Supports screen reader navigation
 *   - Respects user font size preferences
 */

@theme {
  /* Font Families - Base */
  --font-heading: ${headingFamily};
  --font-body: ${bodyFamily};
  --font-ui: ${uiFamily};
  
  /* Extended Font Family Definitions */
  --font-family-heading: ${headingFamily};
  --font-family-body: ${bodyFamily};
  --font-family-ui: ${uiFamily};
  
  /* Typography Weights - Base */
  --font-weight-heading: ${headingConfig.weight};
  --font-weight-body: ${bodyConfig.weight};
  --font-weight-ui: ${uiConfig.weight};
  
  /* Letter Spacing - Base */
  --letter-spacing-heading: ${headingConfig.tracking}em;
  --letter-spacing-body: ${bodyConfig.tracking}em;
  --letter-spacing-ui: ${uiConfig.tracking}em;
  
  /* Line Height - Base */
  --line-height-heading: ${headingConfig.leading};
  --line-height-body: ${bodyConfig.leading};
  --line-height-ui: ${uiConfig.leading};`

  // Add element-specific theme variables for headings
  Object.keys(config.headings || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.headings[element]
      tailwindConfig += `
  --font-heading-${element}: ${getFontFamily(elemConfig.family, elemConfig.category)};
  --font-weight-heading-${element}: ${elemConfig.weight};
  --letter-spacing-heading-${element}: ${elemConfig.tracking}em;
  --line-height-heading-${element}: ${elemConfig.leading};`
    }
  })

  // Add element-specific theme variables for body
  Object.keys(config.body || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.body[element]
      tailwindConfig += `
  --font-body-${element}: ${getFontFamily(elemConfig.family, elemConfig.category)};
  --font-weight-body-${element}: ${elemConfig.weight};
  --letter-spacing-body-${element}: ${elemConfig.tracking}em;
  --line-height-body-${element}: ${elemConfig.leading};`
    }
  })

  // Add element-specific theme variables for ui
  Object.keys(config.ui || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.ui[element]
      tailwindConfig += `
  --font-ui-${element}: ${getFontFamily(elemConfig.family, elemConfig.category)};
  --font-weight-ui-${element}: ${elemConfig.weight};
  --letter-spacing-ui-${element}: ${elemConfig.tracking}em;
  --line-height-ui-${element}: ${elemConfig.leading};`
    }
  })

  tailwindConfig += `
}

/* Custom Utility Classes - Base */
/* Usage: class="text-heading-xl" */
.text-heading-xl {
  font-family: var(--font-heading);
  font-weight: var(--font-weight-heading);
  letter-spacing: var(--letter-spacing-heading);
  line-height: var(--line-height-heading);
  text-transform: ${headingConfig.transform};
}

.text-heading-lg {
  font-family: var(--font-heading);
  font-weight: var(--font-weight-heading);
  letter-spacing: var(--letter-spacing-heading);
  line-height: var(--line-height-heading);
  text-transform: ${headingConfig.transform};
}

.text-heading-base {
  font-family: var(--font-heading);
  font-weight: var(--font-weight-heading);
  letter-spacing: var(--letter-spacing-heading);
  line-height: var(--line-height-heading);
  text-transform: ${headingConfig.transform};
}

.text-body-lg {
  font-family: var(--font-body);
  font-weight: var(--font-weight-body);
  letter-spacing: var(--letter-spacing-body);
  line-height: var(--line-height-body);
  text-transform: ${bodyConfig.transform};
}

.text-body-base {
  font-family: var(--font-body);
  font-weight: var(--font-weight-body);
  letter-spacing: var(--letter-spacing-body);
  line-height: var(--line-height-body);
  text-transform: ${bodyConfig.transform};
}

.text-body-sm {
  font-family: var(--font-body);
  font-weight: var(--font-weight-body);
  letter-spacing: var(--letter-spacing-body);
  line-height: var(--line-height-body);
  text-transform: ${bodyConfig.transform};
}

.text-ui {
  font-family: var(--font-ui);
  font-weight: var(--font-weight-ui);
  letter-spacing: var(--letter-spacing-ui);
  line-height: var(--line-height-ui);
  text-transform: ${uiConfig.transform};
}

/* Element-Specific Utility Classes */
/* Body Prose Elements */
.text-body-paragraph {
  font-family: var(--font-body-paragraph, var(--font-body));
  font-weight: var(--font-weight-body-paragraph, var(--font-weight-body));
  letter-spacing: var(--letter-spacing-body-paragraph, var(--letter-spacing-body));
  line-height: var(--line-height-body-paragraph, var(--line-height-body));
}

.text-body-strong {
  font-family: var(--font-body-strong, var(--font-body));
  font-weight: var(--font-weight-body-strong, var(--font-weight-body));
  letter-spacing: var(--letter-spacing-body-strong, var(--letter-spacing-body));
  line-height: var(--line-height-body-strong, var(--line-height-body));
}

.text-body-emphasis {
  font-family: var(--font-body-emphasis, var(--font-body));
  font-weight: var(--font-weight-body-emphasis, var(--font-weight-body));
  letter-spacing: var(--letter-spacing-body-emphasis, var(--letter-spacing-body));
  line-height: var(--line-height-body-emphasis, var(--line-height-body));
  font-style: italic;
}

.text-body-code {
  font-family: var(--font-body-code, var(--font-body));
  font-weight: var(--font-weight-body-code, var(--font-weight-body));
  letter-spacing: var(--letter-spacing-body-code, var(--letter-spacing-body));
  line-height: var(--line-height-body-code, var(--line-height-body));
}

.text-body-link {
  font-family: var(--font-body-link, var(--font-body));
  font-weight: var(--font-weight-body-link, var(--font-weight-body));
  letter-spacing: var(--letter-spacing-body-link, var(--letter-spacing-body));
  line-height: var(--line-height-body-link, var(--line-height-body));
}

.text-body-blockquote {
  font-family: var(--font-body-blockquote, var(--font-body));
  font-weight: var(--font-weight-body-blockquote, var(--font-weight-body));
  letter-spacing: var(--letter-spacing-body-blockquote, var(--letter-spacing-body));
  line-height: var(--line-height-body-blockquote, var(--line-height-body));
}`

  return tailwindConfig.trim()
}

/**
 * Generate Tailwind Typography (Prose) Configuration
 * Creates configuration for @tailwindcss/typography plugin
 *
 * @param {Object} config - Typography configuration object
 * @returns {string} Prose configuration CSS
 *
 * @example
 * // Installation:
 * npm install @tailwindcss/typography
 *
 * // Usage in HTML:
 * <article class="prose">
 *   <h1>Article Title</h1>
 *   <p>Article content with automatic typography styling.</p>
 * </article>
 *
 * // With modifiers:
 * <div class="prose prose-lg prose-slate">
 *   Large prose content with slate color scheme
 * </div>
 *
 * // Responsive prose:
 * <article class="prose prose-sm md:prose-base lg:prose-lg">
 *   Responsive prose content
 * </article>
 */
export const generateProseConfig = config => {
  const getRoleConfig = role => config[role]?.all || {}

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')

  const headingFamily = getFontFamily(
    headingConfig.family,
    headingConfig.category
  )
  const bodyFamily = getFontFamily(bodyConfig.family, bodyConfig.category)

  // Get element-specific body configs
  const paragraphConfig = config.body?.paragraph || bodyConfig
  const strongConfig = config.body?.strong || bodyConfig
  const emphasisConfig = config.body?.emphasis || bodyConfig
  const blockquoteConfig = config.body?.blockquote || bodyConfig
  const codeConfig = config.body?.code || bodyConfig
  const linkConfig = config.body?.link || bodyConfig

  let proseConfig = `/**
 * @tailwindcss/typography Prose Configuration
 * Generated by TypePalette
 * 
 * Installation:
 *   npm install @tailwindcss/typography
 * 
 * Then add to your tailwind.config.js:
 *   plugins: [require('@tailwindcss/typography')]
 * 
 * Usage:
 *   <article class="prose">
 *     <h1>Your heading</h1>
 *     <p>Your content</p>
 *   </article>
 * 
 * Prose Modifiers:
 *   - prose-sm: Smaller text
 *   - prose-lg: Larger text
 *   - prose-xl: Extra large text
 *   - prose-2xl: 2x large text
 *   - prose-slate: Slate color scheme
 *   - prose-gray: Gray color scheme
 *   - prose-invert: Inverted colors (for dark mode)
 * 
 * Best Practices:
 *   - Use prose for long-form content (articles, blog posts)
 *   - Combine with prose modifiers for different sizes
 *   - Use prose-invert for dark mode support
 */

@theme {
  /* Prose Font Families */
  --prose-body: ${bodyFamily};
  --prose-headings: ${headingFamily};
  
  /* Prose Typography Settings - Base */
  --prose-body-weight: ${bodyConfig.weight};
  --prose-headings-weight: ${headingConfig.weight};
  --prose-body-leading: ${bodyConfig.leading};
  --prose-headings-leading: ${headingConfig.leading};
  --prose-body-tracking: ${bodyConfig.tracking}em;
  --prose-headings-tracking: ${headingConfig.tracking}em;
  
  /* Prose Element-Specific Settings */
  --prose-paragraph-weight: ${paragraphConfig.weight};
  --prose-paragraph-family: ${getFontFamily(paragraphConfig.family, paragraphConfig.category)};
  --prose-strong-weight: ${strongConfig.weight};
  --prose-strong-family: ${getFontFamily(strongConfig.family, strongConfig.category)};
  --prose-emphasis-weight: ${emphasisConfig.weight};
  --prose-emphasis-family: ${getFontFamily(emphasisConfig.family, emphasisConfig.category)};
  --prose-blockquote-weight: ${blockquoteConfig.weight};
  --prose-blockquote-family: ${getFontFamily(blockquoteConfig.family, blockquoteConfig.category)};
  --prose-code-weight: ${codeConfig.weight};
  --prose-code-family: ${getFontFamily(codeConfig.family, codeConfig.category)};
  --prose-link-weight: ${linkConfig.weight};
  --prose-link-family: ${getFontFamily(linkConfig.family, linkConfig.category)};
}

/* Customize Prose Classes */
.prose {
  --tw-prose-body: var(--prose-body);
  --tw-prose-headings: var(--prose-headings);
  --tw-prose-body-weight: var(--prose-body-weight);
  --tw-prose-headings-weight: var(--prose-headings-weight);
  --tw-prose-body-leading: var(--prose-body-leading);
  --tw-prose-headings-leading: var(--prose-headings-leading);
  --tw-prose-body-tracking: var(--prose-body-tracking);
  --tw-prose-headings-tracking: var(--prose-headings-tracking);
}

/* Element-Specific Prose Styles */
.prose p {
  font-weight: var(--prose-paragraph-weight);
  font-family: var(--prose-paragraph-family);
}

.prose strong {
  font-weight: var(--prose-strong-weight);
  font-family: var(--prose-strong-family);
}

.prose em {
  font-weight: var(--prose-emphasis-weight);
  font-family: var(--prose-emphasis-family);
}

.prose blockquote {
  font-weight: var(--prose-blockquote-weight);
  font-family: var(--prose-blockquote-family);
}

.prose code {
  font-weight: var(--prose-code-weight);
  font-family: var(--prose-code-family);
}

.prose a {
  font-weight: var(--prose-link-weight);
  font-family: var(--prose-link-family);
}

/* Usage in HTML: <article class="prose">...</article> */
`

  return proseConfig.trim()
}

export const generateJSONTokens = config => {
  const getRoleConfig = role => config[role]?.all || {}

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  const tokens = {
    typography: {
      headings: {
        all: {
          fontFamily: headingConfig.family,
          fontCategory: headingConfig.category,
          fontWeight: headingConfig.weight,
          letterSpacing: `${headingConfig.tracking}em`,
          lineHeight: headingConfig.leading,
          textTransform: headingConfig.transform
        }
      },
      body: {
        all: {
          fontFamily: bodyConfig.family,
          fontCategory: bodyConfig.category,
          fontWeight: bodyConfig.weight,
          letterSpacing: `${bodyConfig.tracking}em`,
          lineHeight: bodyConfig.leading,
          textTransform: bodyConfig.transform
        }
      },
      ui: {
        all: {
          fontFamily: uiConfig.family,
          fontCategory: uiConfig.category,
          fontWeight: uiConfig.weight,
          letterSpacing: `${uiConfig.tracking}em`,
          lineHeight: uiConfig.leading,
          textTransform: uiConfig.transform
        }
      }
    }
  }

  // Add element-specific configurations for headings
  Object.keys(config.headings || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.headings[element]
      tokens.typography.headings[element] = {
        fontFamily: elemConfig.family,
        fontCategory: elemConfig.category,
        fontWeight: elemConfig.weight,
        letterSpacing: `${elemConfig.tracking}em`,
        lineHeight: elemConfig.leading,
        textTransform: elemConfig.transform
      }
    }
  })

  // Add element-specific configurations for body
  Object.keys(config.body || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.body[element]
      tokens.typography.body[element] = {
        fontFamily: elemConfig.family,
        fontCategory: elemConfig.category,
        fontWeight: elemConfig.weight,
        letterSpacing: `${elemConfig.tracking}em`,
        lineHeight: elemConfig.leading,
        textTransform: elemConfig.transform
      }
    }
  })

  // Add element-specific configurations for ui
  Object.keys(config.ui || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.ui[element]
      tokens.typography.ui[element] = {
        fontFamily: elemConfig.family,
        fontCategory: elemConfig.category,
        fontWeight: elemConfig.weight,
        letterSpacing: `${elemConfig.tracking}em`,
        lineHeight: elemConfig.leading,
        textTransform: elemConfig.transform
      }
    }
  })

  return JSON.stringify(tokens, null, 2)
}

/**
 * Generate Style Dictionary-compatible design tokens
 * Follows Style Dictionary format with $type annotations for proper transformation
 * @param {Object} config - Typography configuration object
 * @returns {string} JSON string of Style Dictionary tokens
 */
export const generateStyleDictionaryTokens = config => {
  const getRoleConfig = role => config[role]?.all || {}
  const getFontFamily = (family, category) => {
    const fallback = category.toLowerCase().includes('serif')
      ? 'serif'
      : 'sans-serif'
    return `"${family}", ${fallback}`
  }

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  const tokens = {
    typography: {
      heading: {
        fontFamily: {
          $type: 'fontFamily',
          $value: getFontFamily(headingConfig.family, headingConfig.category)
        },
        fontWeight: {
          $type: 'fontWeight',
          $value: headingConfig.weight
        },
        letterSpacing: {
          $type: 'letterSpacing',
          $value: `${headingConfig.tracking}em`
        },
        lineHeight: {
          $type: 'lineHeight',
          $value: headingConfig.leading
        },
        textTransform: {
          $type: 'textTransform',
          $value: headingConfig.transform
        }
      },
      body: {
        fontFamily: {
          $type: 'fontFamily',
          $value: getFontFamily(bodyConfig.family, bodyConfig.category)
        },
        fontWeight: {
          $type: 'fontWeight',
          $value: bodyConfig.weight
        },
        letterSpacing: {
          $type: 'letterSpacing',
          $value: `${bodyConfig.tracking}em`
        },
        lineHeight: {
          $type: 'lineHeight',
          $value: bodyConfig.leading
        },
        textTransform: {
          $type: 'textTransform',
          $value: bodyConfig.transform
        }
      },
      ui: {
        fontFamily: {
          $type: 'fontFamily',
          $value: getFontFamily(uiConfig.family, uiConfig.category)
        },
        fontWeight: {
          $type: 'fontWeight',
          $value: uiConfig.weight
        },
        letterSpacing: {
          $type: 'letterSpacing',
          $value: `${uiConfig.tracking}em`
        },
        lineHeight: {
          $type: 'lineHeight',
          $value: uiConfig.leading
        },
        textTransform: {
          $type: 'textTransform',
          $value: uiConfig.transform
        }
      }
    }
  }

  // Add element-specific tokens for headings
  Object.keys(config.headings || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.headings[element]
      tokens.typography.heading[element] = {
        fontFamily: {
          $type: 'fontFamily',
          $value: getFontFamily(elemConfig.family, elemConfig.category)
        },
        fontWeight: {
          $type: 'fontWeight',
          $value: elemConfig.weight
        },
        letterSpacing: {
          $type: 'letterSpacing',
          $value: `${elemConfig.tracking}em`
        },
        lineHeight: {
          $type: 'lineHeight',
          $value: elemConfig.leading
        },
        textTransform: {
          $type: 'textTransform',
          $value: elemConfig.transform
        }
      }
    }
  })

  // Add element-specific tokens for body
  Object.keys(config.body || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.body[element]
      tokens.typography.body[element] = {
        fontFamily: {
          $type: 'fontFamily',
          $value: getFontFamily(elemConfig.family, elemConfig.category)
        },
        fontWeight: {
          $type: 'fontWeight',
          $value: elemConfig.weight
        },
        letterSpacing: {
          $type: 'letterSpacing',
          $value: `${elemConfig.tracking}em`
        },
        lineHeight: {
          $type: 'lineHeight',
          $value: elemConfig.leading
        },
        textTransform: {
          $type: 'textTransform',
          $value: elemConfig.transform
        }
      }
    }
  })

  // Add element-specific tokens for ui
  Object.keys(config.ui || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.ui[element]
      tokens.typography.ui[element] = {
        fontFamily: {
          $type: 'fontFamily',
          $value: getFontFamily(elemConfig.family, elemConfig.category)
        },
        fontWeight: {
          $type: 'fontWeight',
          $value: elemConfig.weight
        },
        letterSpacing: {
          $type: 'letterSpacing',
          $value: `${elemConfig.tracking}em`
        },
        lineHeight: {
          $type: 'lineHeight',
          $value: elemConfig.leading
        },
        textTransform: {
          $type: 'textTransform',
          $value: elemConfig.transform
        }
      }
    }
  })

  return JSON.stringify(tokens, null, 2)
}

/**
 * Generate W3C Design Tokens format (compatible with Figma)
 * Uses standard W3C format with $type properties
 * @param {Object} config - Typography configuration object
 * @returns {string} JSON string of W3C design tokens
 */
export const generateW3CTokens = config => {
  return generateStyleDictionaryTokens(config) // W3C format is the same as Style Dictionary
}

/**
 * Generate Figma Variables-compatible token format
 * Structured for import into Figma Variables API
 * @param {Object} config - Typography configuration object
 * @returns {string} JSON string of Figma-compatible tokens
 */
export const generateFigmaTokens = config => {
  const getRoleConfig = role => config[role]?.all || {}
  const getFontFamily = (family, category) => {
    const fallback = category.toLowerCase().includes('serif')
      ? 'serif'
      : 'sans-serif'
    return `"${family}", ${fallback}`
  }

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  // Figma Variables format with metadata
  const figmaTokens = {
    $schema: 'https://schemas.figma.com/v1/variables',
    version: '1.0.0',
    collections: [
      {
        name: 'Typography',
        modes: [
          {
            name: 'Default',
            variables: [
              {
                name: 'heading/fontFamily',
                type: 'STRING',
                value: getFontFamily(
                  headingConfig.family,
                  headingConfig.category
                )
              },
              {
                name: 'heading/fontWeight',
                type: 'FLOAT',
                value: parseFloat(headingConfig.weight)
              },
              {
                name: 'heading/letterSpacing',
                type: 'FLOAT',
                value: parseFloat(headingConfig.tracking)
              },
              {
                name: 'heading/lineHeight',
                type: 'FLOAT',
                value: parseFloat(headingConfig.leading)
              },
              {
                name: 'body/fontFamily',
                type: 'STRING',
                value: getFontFamily(bodyConfig.family, bodyConfig.category)
              },
              {
                name: 'body/fontWeight',
                type: 'FLOAT',
                value: parseFloat(bodyConfig.weight)
              },
              {
                name: 'body/letterSpacing',
                type: 'FLOAT',
                value: parseFloat(bodyConfig.tracking)
              },
              {
                name: 'body/lineHeight',
                type: 'FLOAT',
                value: parseFloat(bodyConfig.leading)
              },
              {
                name: 'ui/fontFamily',
                type: 'STRING',
                value: getFontFamily(uiConfig.family, uiConfig.category)
              },
              {
                name: 'ui/fontWeight',
                type: 'FLOAT',
                value: parseFloat(uiConfig.weight)
              },
              {
                name: 'ui/letterSpacing',
                type: 'FLOAT',
                value: parseFloat(uiConfig.tracking)
              },
              {
                name: 'ui/lineHeight',
                type: 'FLOAT',
                value: parseFloat(uiConfig.leading)
              }
            ]
          }
        ]
      }
    ]
  }

  // Add element-specific variables
  Object.keys(config.headings || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.headings[element]
      figmaTokens.collections[0].modes[0].variables.push(
        {
          name: `heading/${element}/fontFamily`,
          type: 'STRING',
          value: getFontFamily(elemConfig.family, elemConfig.category)
        },
        {
          name: `heading/${element}/fontWeight`,
          type: 'FLOAT',
          value: parseFloat(elemConfig.weight)
        },
        {
          name: `heading/${element}/letterSpacing`,
          type: 'FLOAT',
          value: parseFloat(elemConfig.tracking)
        },
        {
          name: `heading/${element}/lineHeight`,
          type: 'FLOAT',
          value: parseFloat(elemConfig.leading)
        }
      )
    }
  })

  Object.keys(config.body || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.body[element]
      figmaTokens.collections[0].modes[0].variables.push(
        {
          name: `body/${element}/fontFamily`,
          type: 'STRING',
          value: getFontFamily(elemConfig.family, elemConfig.category)
        },
        {
          name: `body/${element}/fontWeight`,
          type: 'FLOAT',
          value: parseFloat(elemConfig.weight)
        },
        {
          name: `body/${element}/letterSpacing`,
          type: 'FLOAT',
          value: parseFloat(elemConfig.tracking)
        },
        {
          name: `body/${element}/lineHeight`,
          type: 'FLOAT',
          value: parseFloat(elemConfig.leading)
        }
      )
    }
  })

  Object.keys(config.ui || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.ui[element]
      figmaTokens.collections[0].modes[0].variables.push(
        {
          name: `ui/${element}/fontFamily`,
          type: 'STRING',
          value: getFontFamily(elemConfig.family, elemConfig.category)
        },
        {
          name: `ui/${element}/fontWeight`,
          type: 'FLOAT',
          value: parseFloat(elemConfig.weight)
        },
        {
          name: `ui/${element}/letterSpacing`,
          type: 'FLOAT',
          value: parseFloat(elemConfig.tracking)
        },
        {
          name: `ui/${element}/lineHeight`,
          type: 'FLOAT',
          value: parseFloat(elemConfig.leading)
        }
      )
    }
  })

  return JSON.stringify(figmaTokens, null, 2)
}

/**
 * Generate Style Dictionary configuration file
 * Creates config.json for Style Dictionary to process tokens
 * @param {Object} config - Typography configuration object (unused but kept for consistency)
 * @returns {string} JSON string of Style Dictionary config
 */
export const generateStyleDictionaryConfig = () => {
  const sdConfig = {
    source: ['tokens/**/*.json'],
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: 'build/css/',
        files: [
          {
            destination: 'variables.css',
            format: 'css/variables',
            options: {
              showFileHeader: true
            }
          }
        ]
      },
      scss: {
        transformGroup: 'scss',
        buildPath: 'build/scss/',
        files: [
          {
            destination: '_variables.scss',
            format: 'scss/variables',
            options: {
              showFileHeader: true
            }
          }
        ]
      },
      ios: {
        transformGroup: 'ios',
        buildPath: 'build/ios/',
        files: [
          {
            destination: 'Typography.swift',
            format: 'ios/swift/class.swift',
            className: 'Typography',
            options: {
              showFileHeader: true
            }
          }
        ]
      },
      android: {
        transformGroup: 'android',
        buildPath: 'build/android/',
        files: [
          {
            destination: 'typography.xml',
            format: 'android/xml',
            options: {
              showFileHeader: true
            }
          }
        ]
      },
      json: {
        transformGroup: 'js',
        buildPath: 'build/json/',
        files: [
          {
            destination: 'tokens.json',
            format: 'json/nested'
          }
        ]
      }
    }
  }

  return JSON.stringify(sdConfig, null, 2)
}

/**
 * Generate iOS/SwiftUI typography tokens
 * Creates Swift code with typography constants
 * @param {Object} config - Typography configuration object
 * @returns {string} Swift code for typography system
 */
export const generateIOSExport = config => {
  const getRoleConfig = role => config[role]?.all || {}
  const getFontFamily = (family, category) => {
    return `"${family}"`
  }

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  let swift = `//
// Typography.swift
// Generated by TypePalette
//
// Usage in SwiftUI:
// Text("Hello")
//   .font(.custom(Typography.heading.fontFamily, size: 24))
//   .fontWeight(Typography.heading.fontWeight)
//

import SwiftUI

struct Typography {
    struct Heading {
        static let fontFamily = ${getFontFamily(headingConfig.family, headingConfig.category)}
        static let fontWeight: Font.Weight = .${headingConfig.weight === '700' ? 'bold' : headingConfig.weight === '600' ? 'semibold' : headingConfig.weight === '500' ? 'medium' : 'regular'}
        static let letterSpacing: CGFloat = ${headingConfig.tracking}
        static let lineHeight: CGFloat = ${headingConfig.leading}
    }
    
    struct Body {
        static let fontFamily = ${getFontFamily(bodyConfig.family, bodyConfig.category)}
        static let fontWeight: Font.Weight = .${bodyConfig.weight === '700' ? 'bold' : bodyConfig.weight === '600' ? 'semibold' : bodyConfig.weight === '500' ? 'medium' : 'regular'}
        static let letterSpacing: CGFloat = ${bodyConfig.tracking}
        static let lineHeight: CGFloat = ${bodyConfig.leading}
    }
    
    struct UI {
        static let fontFamily = ${getFontFamily(uiConfig.family, uiConfig.category)}
        static let fontWeight: Font.Weight = .${uiConfig.weight === '700' ? 'bold' : uiConfig.weight === '600' ? 'semibold' : uiConfig.weight === '500' ? 'medium' : 'regular'}
        static let letterSpacing: CGFloat = ${uiConfig.tracking}
        static let lineHeight: CGFloat = ${uiConfig.leading}
    }
}

// SwiftUI Extension for easier usage
extension Font {
    static var heading: Font {
        .custom(Typography.Heading.fontFamily, size: 24)
    }
    
    static var body: Font {
        .custom(Typography.Body.fontFamily, size: 16)
    }
    
    static var ui: Font {
        .custom(Typography.UI.fontFamily, size: 14)
    }
}
`

  return swift.trim()
}

/**
 * Generate Android/XML typography tokens
 * Creates XML resource file for Android typography
 * @param {Object} config - Typography configuration object
 * @returns {string} XML code for Android typography system
 */
export const generateAndroidExport = config => {
  const getRoleConfig = role => config[role]?.all || {}
  const getFontFamily = (family, category) => {
    return family.replace(/\s+/g, '_').toLowerCase()
  }

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  let xml = `<?xml version="1.0" encoding="utf-8"?>
<!--
  Typography Resources
  Generated by TypePalette
  
  Usage in Android:
  <TextView
      android:fontFamily="@font/${getFontFamily(headingConfig.family, headingConfig.category)}"
      android:textStyle="bold"
      android:letterSpacing="${headingConfig.tracking}"
      android:lineSpacingMultiplier="${headingConfig.leading}" />
-->
<resources>
    <!-- Heading Typography -->
    <string name="font_family_heading">${getFontFamily(headingConfig.family, headingConfig.category)}</string>
    <integer name="font_weight_heading">${headingConfig.weight}</integer>
    <dimen name="letter_spacing_heading">${headingConfig.tracking}sp</dimen>
    <dimen name="line_height_heading">${headingConfig.leading}sp</dimen>
    
    <!-- Body Typography -->
    <string name="font_family_body">${getFontFamily(bodyConfig.family, bodyConfig.category)}</string>
    <integer name="font_weight_body">${bodyConfig.weight}</integer>
    <dimen name="letter_spacing_body">${bodyConfig.tracking}sp</dimen>
    <dimen name="line_height_body">${bodyConfig.leading}sp</dimen>
    
    <!-- UI Typography -->
    <string name="font_family_ui">${getFontFamily(uiConfig.family, uiConfig.category)}</string>
    <integer name="font_weight_ui">${uiConfig.weight}</integer>
    <dimen name="letter_spacing_ui">${uiConfig.tracking}sp</dimen>
    <dimen name="line_height_ui">${uiConfig.leading}sp</dimen>
</resources>
`

  return xml.trim()
}

/**
 * Generate React Native typography styles
 * Creates JavaScript/TypeScript code for React Native
 * @param {Object} config - Typography configuration object
 * @returns {string} React Native typography styles code
 */
export const generateReactNativeExport = config => {
  const getRoleConfig = role => config[role]?.all || {}
  const getFontFamily = (family, category) => {
    return `"${family}"`
  }

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  let rnCode = `/**
 * Typography Styles for React Native
 * Generated by TypePalette
 * 
 * Usage:
 * import { typography } from './typography';
 * 
 * <Text style={typography.heading.h1}>Heading</Text>
 * <Text style={typography.body.paragraph}>Body text</Text>
 */

import { StyleSheet, Platform } from 'react-native';

export const typography = StyleSheet.create({
  heading: {
    fontFamily: ${getFontFamily(headingConfig.family, headingConfig.category)},
    fontWeight: '${headingConfig.weight}',
    letterSpacing: ${headingConfig.tracking},
    lineHeight: ${parseFloat(headingConfig.leading) * 16}, // Assuming base font size of 16
  },
  body: {
    fontFamily: ${getFontFamily(bodyConfig.family, bodyConfig.category)},
    fontWeight: '${bodyConfig.weight}',
    letterSpacing: ${bodyConfig.tracking},
    lineHeight: ${parseFloat(bodyConfig.leading) * 16},
  },
  ui: {
    fontFamily: ${getFontFamily(uiConfig.family, uiConfig.category)},
    fontWeight: '${uiConfig.weight}',
    letterSpacing: ${uiConfig.tracking},
    lineHeight: ${parseFloat(uiConfig.leading) * 16},
  },
});

// TypeScript types (if using TypeScript)
export interface TypographyStyles {
  heading: {
    fontFamily: string;
    fontWeight: string;
    letterSpacing: number;
    lineHeight: number;
  };
  body: {
    fontFamily: string;
    fontWeight: string;
    letterSpacing: number;
    lineHeight: number;
  };
  ui: {
    fontFamily: string;
    fontWeight: string;
    letterSpacing: number;
    lineHeight: number;
  };
}
`

  return rnCode.trim()
}

/**
 * Generate Flutter typography theme
 * Creates Dart code for Flutter typography
 * @param {Object} config - Typography configuration object
 * @returns {string} Flutter/Dart code for typography system
 */
export const generateFlutterExport = config => {
  const getRoleConfig = role => config[role]?.all || {}
  const getFontFamily = (family, category) => {
    return `'${family}'`
  }

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  let flutter = `// typography.dart
// Generated by TypePalette
//
// Usage in Flutter:
// Text(
//   'Hello',
//   style: Typography.heading,
// )

import 'package:flutter/material.dart';

class Typography {
  static const TextStyle heading = TextStyle(
    fontFamily: ${getFontFamily(headingConfig.family, headingConfig.category)},
    fontWeight: FontWeight.w${headingConfig.weight},
    letterSpacing: ${headingConfig.tracking},
    height: ${headingConfig.leading},
  );
  
  static const TextStyle body = TextStyle(
    fontFamily: ${getFontFamily(bodyConfig.family, bodyConfig.category)},
    fontWeight: FontWeight.w${bodyConfig.weight},
    letterSpacing: ${bodyConfig.tracking},
    height: ${bodyConfig.leading},
  );
  
  static const TextStyle ui = TextStyle(
    fontFamily: ${getFontFamily(uiConfig.family, uiConfig.category)},
    fontWeight: FontWeight.w${uiConfig.weight},
    letterSpacing: ${uiConfig.tracking},
    height: ${uiConfig.leading},
  );
}

// Theme extension for easy integration
class TypographyTheme extends ThemeExtension<TypographyTheme> {
  final TextStyle heading;
  final TextStyle body;
  final TextStyle ui;

  const TypographyTheme({
    required this.heading,
    required this.body,
    required this.ui,
  });

  @override
  TypographyTheme copyWith({
    TextStyle? heading,
    TextStyle? body,
    TextStyle? ui,
  }) {
    return TypographyTheme(
      heading: heading ?? this.heading,
      body: body ?? this.body,
      ui: ui ?? this.ui,
    );
  }

  @override
  TypographyTheme lerp(ThemeExtension<TypographyTheme>? other, double t) {
    if (other is! TypographyTheme) {
      return this;
    }
    return TypographyTheme(
      heading: TextStyle.lerp(heading, other.heading, t)!,
      body: TextStyle.lerp(body, other.body, t)!,
      ui: TextStyle.lerp(ui, other.ui, t)!,
    );
  }
}
`

  return flutter.trim()
}

/**
 * Generate CSS-in-JS exports (styled-components, emotion)
 * Creates JavaScript/TypeScript code for CSS-in-JS libraries
 * @param {Object} config - Typography configuration object
 * @returns {string} CSS-in-JS typography code
 */
export const generateCSSInJSExport = config => {
  const getRoleConfig = role => config[role]?.all || {}
  const getFontFamily = (family, category) => {
    const fallback = category.toLowerCase().includes('serif')
      ? 'serif'
      : 'sans-serif'
    return `"${family}", ${fallback}`
  }

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  let cssInJS = `/**
 * Typography Styles for CSS-in-JS (styled-components, emotion)
 * Generated by TypePalette
 * 
 * Usage with styled-components:
 * import { typography } from './typography';
 * 
 * const Heading = styled.h1\`
 *   \${typography.heading}
 * \`;
 * 
 * Usage with emotion:
 * import { css } from '@emotion/react';
 * import { typography } from './typography';
 * 
 * <h1 css={typography.heading}>Heading</h1>
 */

// For styled-components
export const typography = {
  heading: \`
    font-family: ${getFontFamily(headingConfig.family, headingConfig.category)};
    font-weight: ${headingConfig.weight};
    letter-spacing: ${headingConfig.tracking}em;
    line-height: ${headingConfig.leading};
    text-transform: ${headingConfig.transform};
  \`,
  body: \`
    font-family: ${getFontFamily(bodyConfig.family, bodyConfig.category)};
    font-weight: ${bodyConfig.weight};
    letter-spacing: ${bodyConfig.tracking}em;
    line-height: ${bodyConfig.leading};
    text-transform: ${bodyConfig.transform};
  \`,
  ui: \`
    font-family: ${getFontFamily(uiConfig.family, uiConfig.category)};
    font-weight: ${uiConfig.weight};
    letter-spacing: ${uiConfig.tracking}em;
    line-height: ${uiConfig.leading};
    text-transform: ${uiConfig.transform};
  \`,
};

// For emotion (CSS object syntax)
export const typographyCSS = {
  heading: {
    fontFamily: ${getFontFamily(headingConfig.family, headingConfig.category)},
    fontWeight: ${headingConfig.weight},
    letterSpacing: \`${headingConfig.tracking}em\`,
    lineHeight: ${headingConfig.leading},
    textTransform: ${headingConfig.transform},
  },
  body: {
    fontFamily: ${getFontFamily(bodyConfig.family, bodyConfig.category)},
    fontWeight: ${bodyConfig.weight},
    letterSpacing: \`${bodyConfig.tracking}em\`,
    lineHeight: ${bodyConfig.leading},
    textTransform: ${bodyConfig.transform},
  },
  ui: {
    fontFamily: ${getFontFamily(uiConfig.family, uiConfig.category)},
    fontWeight: ${uiConfig.weight},
    letterSpacing: \`${uiConfig.tracking}em\`,
    lineHeight: ${uiConfig.leading},
    textTransform: ${uiConfig.transform},
  },
};

// TypeScript types
export interface TypographyStyles {
  heading: string;
  body: string;
  ui: string;
}

export interface TypographyCSS {
  heading: React.CSSProperties;
  body: React.CSSProperties;
  ui: React.CSSProperties;
}
`

  return cssInJS.trim()
}

/**
 * Generate TypeScript Type Definitions
 * Creates TypeScript interfaces for typography system
 * @param {Object} config - Typography configuration object
 * @returns {string} TypeScript type definitions
 */
export const generateTypeScriptTypes = config => {
  return `/**
 * TypeScript Type Definitions for Typography System
 * Generated by TypePalette
 * 
 * Usage:
 *   import type { TypographyConfig, TypographyRole } from './typography.types';
 * 
 *   const heading: TypographyRole = {
 *     fontFamily: 'var(--font-heading)',
 *     fontWeight: 'var(--heading-weight)',
 *   };
 */

export interface TypographyConfig {
  headings: TypographyRole;
  body: TypographyRole;
  ui: TypographyRole;
}

export interface TypographyRole {
  fontFamily: string;
  fontWeight: string | number;
  letterSpacing: string;
  lineHeight: string | number;
  textTransform: 'none' | 'uppercase' | 'lowercase' | 'capitalize';
}

export interface TypographyElementConfig extends TypographyRole {
  element: string;
}

export interface CSSVariables {
  '--font-heading': string;
  '--font-body': string;
  '--font-ui': string;
  '--heading-weight': string;
  '--heading-tracking': string;
  '--heading-leading': string;
  '--heading-transform': string;
  '--body-weight': string;
  '--body-tracking': string;
  '--body-leading': string;
  '--body-transform': string;
  '--ui-weight': string;
  '--ui-tracking': string;
  '--ui-leading': string;
  '--ui-transform': string;
}

// React component props with typography
export interface TypographyProps {
  variant?: 'heading' | 'body' | 'ui';
  element?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'span';
  className?: string;
  children: React.ReactNode;
}

// Utility type for responsive typography
export type ResponsiveTypography = {
  base: TypographyRole;
  sm?: TypographyRole;
  md?: TypographyRole;
  lg?: TypographyRole;
  xl?: TypographyRole;
};
`.trim()
}

/**
 * Generate React Component Examples
 * Creates example React components using the typography system
 * @param {Object} config - Typography configuration object
 * @returns {string} React component examples code
 */
export const generateReactExamples = config => {
  const getRoleConfig = role => config[role]?.all || {}
  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')

  return `/**
 * React Component Examples
 * Generated by TypePalette
 * 
 * These examples demonstrate how to use the typography system in React components.
 * Copy and adapt these components for your project.
 */

import React from 'react';
import './typography.css'; // Import your CSS variables

/**
 * Typography Component
 * A reusable component for consistent typography
 */
interface TypographyProps {
  variant?: 'heading' | 'body' | 'ui';
  as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'span' | 'div';
  className?: string;
  children: React.ReactNode;
}

export const Typography: React.FC<TypographyProps> = ({
  variant = 'body',
  as: Component = 'p',
  className = '',
  children,
}) => {
  const variantClasses = {
    heading: 'typography-heading',
    body: 'typography-body',
    ui: 'typography-ui',
  };

  return (
    <Component className={\`\${variantClasses[variant]} \${className}\`}>
      {children}
    </Component>
  );
};

/**
 * Heading Component
 * Pre-configured heading component
 */
interface HeadingProps {
  level?: 1 | 2 | 3 | 4 | 5 | 6;
  className?: string;
  children: React.ReactNode;
}

export const Heading: React.FC<HeadingProps> = ({
  level = 1,
  className = '',
  children,
}) => {
  const HeadingTag = \`h\${level}\` as keyof JSX.IntrinsicElements;
  
  return (
    <HeadingTag
      className={\`typography-heading heading-\${level} \${className}\`}
      style={{
        fontFamily: 'var(--font-heading)',
        fontWeight: 'var(--heading-weight)',
        letterSpacing: 'var(--heading-tracking)',
        lineHeight: 'var(--heading-leading)',
        textTransform: 'var(--heading-transform)',
      }}
    >
      {children}
    </HeadingTag>
  );
};

/**
 * Body Text Component
 * Pre-configured body text component
 */
interface BodyTextProps {
  className?: string;
  children: React.ReactNode;
}

export const BodyText: React.FC<BodyTextProps> = ({
  className = '',
  children,
}) => {
  return (
    <p
      className={\`typography-body \${className}\`}
      style={{
        fontFamily: 'var(--font-body)',
        fontWeight: 'var(--body-weight)',
        letterSpacing: 'var(--body-tracking)',
        lineHeight: 'var(--body-leading)',
        textTransform: 'var(--body-transform)',
      }}
    >
      {children}
    </p>
  );
};

/**
 * Usage Examples:
 * 
 * // Basic usage
 * <Typography variant="heading" as="h1">Title</Typography>
 * <Typography variant="body">Body text</Typography>
 * 
 * // Using pre-configured components
 * <Heading level={1}>Main Title</Heading>
 * <Heading level={2}>Subtitle</Heading>
 * <BodyText>This is body text with proper typography.</BodyText>
 * 
 * // With Tailwind CSS
 * <Heading level={1} className="text-4xl md:text-5xl lg:text-6xl">
 *   Responsive Heading
 * </Heading>
 * 
 * // With custom styles
 * <BodyText className="text-gray-600 dark:text-gray-300">
 *   Body text with color utilities
 * </BodyText>
 */
`.trim()
}

/**
 * Generate Next.js Font Installation Code
 * Creates Next.js code using next/font/google for optimized font loading
 *
 * @param {Object} config - Typography configuration object
 * @returns {string} Next.js font configuration code
 *
 * @example
 * // This code should be placed in app/layout.jsx (App Router) or pages/_app.jsx (Pages Router)
 * // The fonts will be automatically optimized and self-hosted by Next.js
 *
 * // TypeScript support:
 * // Add type definitions if using TypeScript
 * // The font variables are automatically typed
 *
 * // Usage in components:
 * <h1 className={headingFont.className}>Heading</h1>
 * <p className={bodyFont.className}>Body text</p>
 *
 * // Or use CSS variables:
 * <h1 style={{ fontFamily: 'var(--font-heading)' }}>Heading</h1>
 */
export const generateNextJSInstall = config => {
  // Convert font names to Next.js format (e.g., "Playfair Display" -> "Playfair_Display")
  const toNextJSFontName = name => name.replace(/\s+/g, '_')

  const getRoleConfig = role => config[role]?.all || {}

  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  // Collect all unique fonts from all roles and elements
  const fontMap = new Map()

  // Add base fonts
  fontMap.set(headingConfig.family, {
    name: headingConfig.family,
    weights: new Set([headingConfig.weight]),
    variables: ['--font-heading']
  })
  fontMap.set(bodyConfig.family, {
    name: bodyConfig.family,
    weights: new Set([bodyConfig.weight]),
    variables: ['--font-body']
  })
  fontMap.set(uiConfig.family, {
    name: uiConfig.family,
    weights: new Set([uiConfig.weight]),
    variables: ['--font-ui']
  })

  // Add element-specific fonts
  Object.keys(config.headings || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.headings[element]
      if (!fontMap.has(elemConfig.family)) {
        fontMap.set(elemConfig.family, {
          name: elemConfig.family,
          weights: new Set(),
          variables: []
        })
      }
      fontMap.get(elemConfig.family).weights.add(elemConfig.weight)
      fontMap.get(elemConfig.family).variables.push(`--font-heading-${element}`)
    }
  })

  Object.keys(config.body || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.body[element]
      if (!fontMap.has(elemConfig.family)) {
        fontMap.set(elemConfig.family, {
          name: elemConfig.family,
          weights: new Set(),
          variables: []
        })
      }
      fontMap.get(elemConfig.family).weights.add(elemConfig.weight)
      fontMap.get(elemConfig.family).variables.push(`--font-body-${element}`)
    }
  })

  Object.keys(config.ui || {}).forEach(element => {
    if (element !== 'all') {
      const elemConfig = config.ui[element]
      if (!fontMap.has(elemConfig.family)) {
        fontMap.set(elemConfig.family, {
          name: elemConfig.family,
          weights: new Set(),
          variables: []
        })
      }
      fontMap.get(elemConfig.family).weights.add(elemConfig.weight)
      fontMap.get(elemConfig.family).variables.push(`--font-ui-${element}`)
    }
  })

  const fonts = Array.from(fontMap.values()).map(font => ({
    name: font.name,
    weights: Array.from(font.weights),
    variables: font.variables
  }))

  const imports = fonts.map(font => toNextJSFontName(font.name)).join(', ')
  const fontConfigs = fonts
    .map(font => {
      const nextJSName = toNextJSFontName(font.name)
      const varName =
        font.variables[0].replace('--font-', '').replace(/-[^-]+$/, '') ||
        'font'
      return `const ${varName} = ${nextJSName}({ 
  subsets: ['latin'],
  variable: '${font.variables[0]}',
  weight: [${font.weights.map(w => `'${w}'`).join(', ')}],
  display: 'swap'
})`
    })
    .join('\n\n')

  const classNameVars = fonts
    .map(font => {
      const varName =
        font.variables[0].replace('--font-', '').replace(/-[^-]+$/, '') ||
        'font'
      return `\${${varName}.variable}`
    })
    .join(' ')

  return `/**
 * Next.js Font Configuration
 * Generated by TypePalette
 * 
 * Place this code in:
 *   - app/layout.jsx (App Router) or
 *   - pages/_app.jsx (Pages Router)
 * 
 * Next.js will automatically:
 *   - Optimize font loading
 *   - Self-host fonts for better performance
 *   - Reduce layout shift (CLS)
 *   - Generate font subsets
 * 
 * TypeScript Support:
 *   This code works with TypeScript. Font variables are automatically typed.
 * 
 * Usage Examples:
 * 
 * 1. Using className prop:
 *    <h1 className={headingFont.className}>Heading</h1>
 * 
 * 2. Using CSS variables:
 *    <h1 style={{ fontFamily: 'var(--font-heading)' }}>Heading</h1>
 * 
 * 3. In CSS modules:
 *    .heading {
 *      font-family: var(--font-heading);
 *    }
 * 
 * 4. With Tailwind CSS:
 *    Add to tailwind.config.js:
 *    theme: {
 *      extend: {
 *        fontFamily: {
 *          heading: ['var(--font-heading)'],
 *          body: ['var(--font-body)'],
 *        }
 *      }
 *    }
 */

// app/layout.jsx (App Router) or pages/_app.jsx (Pages Router)
import { ${imports} } from 'next/font/google'

${fontConfigs}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={\`${classNameVars}\`}>
      <body>{children}</body>
    </html>
  )
}

/**
 * Usage in your components:
 * 
 * // Option 1: Use className
 * <h1 className={headingFont.className}>Heading</h1>
 * 
 * // Option 2: Use CSS variables
 * <h1 style={{ fontFamily: 'var(--font-heading)' }}>Heading</h1>
 * 
 * // Option 3: Use in CSS/SCSS
 * .heading {
 *   font-family: var(--font-heading);
 *   font-weight: var(--heading-weight);
 * }
 */
`.trim()
}

/**
 * Generate Vite Installation Instructions
 * Creates HTML and CSS setup for Vite projects
 *
 * @param {Object} config - Typography configuration object
 * @returns {string} Vite installation code
 *
 * @example
 * // 1. Add Google Fonts link to index.html
 * // 2. Import CSS in main.jsx/main.tsx
 * // 3. Use CSS variables in your components
 *
 * // In React components:
 * <h1 style={{ fontFamily: 'var(--font-heading)' }}>Heading</h1>
 *
 * // In CSS modules:
 * .heading {
 *   font-family: var(--font-heading);
 * }
 */
export const generateViteInstall = config => {
  // Collect all unique font families
  const fontNames = new Set()

  // Add base fonts
  fontNames.add(config.headings?.all?.family)
  fontNames.add(config.body?.all?.family)
  fontNames.add(config.ui?.all?.family)

  // Add element-specific fonts
  Object.values(config.headings || {}).forEach(elemConfig => {
    if (elemConfig?.family) fontNames.add(elemConfig.family)
  })
  Object.values(config.body || {}).forEach(elemConfig => {
    if (elemConfig?.family) fontNames.add(elemConfig.family)
  })
  Object.values(config.ui || {}).forEach(elemConfig => {
    if (elemConfig?.family) fontNames.add(elemConfig.family)
  })

  const googleFontsUrl = Array.from(fontNames)
    .filter(Boolean)
    .map(name => name.replace(/\s+/g, '+'))
    .join('&family=')

  return `/**
 * Vite Installation Guide
 * Generated by TypePalette
 * 
 * Follow these steps to set up typography in your Vite project:
 * 
 * STEP 1: Add Google Fonts to index.html
 * Add the following <link> tags in the <head> section of your index.html
 */

<!-- index.html -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=${googleFontsUrl}&display=swap" rel="stylesheet">

/**
 * STEP 2: Import CSS in main.jsx or main.tsx
 * Add this import to your main entry file
 */

// main.jsx or main.tsx
import './index.css'

/**
 * STEP 3: Add CSS Variables to index.css
 * Copy the CSS variables below into your index.css file
 * 
 * Usage in React components:
 *   <h1 style={{ fontFamily: 'var(--font-heading)' }}>Heading</h1>
 * 
 * Usage in CSS modules:
 *   .heading {
 *     font-family: var(--font-heading);
 *     font-weight: var(--heading-weight);
 *   }
 * 
 * Usage with Tailwind CSS:
 *   Add to tailwind.config.js:
 *   theme: {
 *     extend: {
 *       fontFamily: {
 *         heading: ['var(--font-heading)'],
 *         body: ['var(--font-body)'],
 *       }
 *     }
 *   }
 */

/* index.css */
${generateCSSExport(config)}
`.trim()
}

export const generateHTMLInstall = config => {
  // Collect all unique font families
  const fontNames = new Set()

  // Add base fonts
  fontNames.add(config.headings?.all?.family)
  fontNames.add(config.body?.all?.family)
  fontNames.add(config.ui?.all?.family)

  // Add element-specific fonts
  Object.values(config.headings || {}).forEach(elemConfig => {
    if (elemConfig?.family) fontNames.add(elemConfig.family)
  })
  Object.values(config.body || {}).forEach(elemConfig => {
    if (elemConfig?.family) fontNames.add(elemConfig.family)
  })
  Object.values(config.ui || {}).forEach(elemConfig => {
    if (elemConfig?.family) fontNames.add(elemConfig.family)
  })

  const googleFontsUrl = Array.from(fontNames)
    .filter(Boolean)
    .map(name => name.replace(/\s+/g, '+'))
    .join('&family=')

  return `# Typography Configuration

This package contains your typography configuration files.

## Installation

### 1. Add Google Fonts

Add the following to your HTML \`<head>\`:

\`\`\`html
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=${googleFontsUrl}&display=swap" rel="stylesheet">
\`\`\`

### 2. Include CSS Variables

Link to \`css-variables.css\` in your HTML:

\`\`\`html
<link rel="stylesheet" href="css-variables.css">
\`\`\`

Or copy the contents of \`css-variables.css\` into your stylesheet.

## Usage

### CSS Variables

Use the CSS variables in your styles:

\`\`\`css
.heading {
  font-family: var(--font-heading);
  font-weight: var(--heading-weight);
  letter-spacing: var(--heading-tracking);
  line-height: var(--heading-leading);
  text-transform: var(--heading-transform);
}

.body {
  font-family: var(--font-body);
  font-weight: var(--body-weight);
  letter-spacing: var(--body-tracking);
  line-height: var(--body-leading);
  text-transform: var(--body-transform);
}

.ui {
  font-family: var(--font-ui);
  font-weight: var(--ui-weight);
  letter-spacing: var(--ui-tracking);
  line-height: var(--ui-leading);
  text-transform: var(--ui-transform);
}
\`\`\`

### HTML Example

\`\`\`html
<h1 style="font-family: var(--font-heading); font-weight: var(--heading-weight);">
  Heading Text
</h1>
<p style="font-family: var(--font-body); font-weight: var(--body-weight);">
  Body text content
</p>
\`\`\`

## Files Included

- \`css-variables.css\` - CSS variables for typography system
- \`tailwind-comprehensive.css\` - Comprehensive Tailwind v4 configuration
- \`tailwind-basic.css\` - Basic Tailwind v4 configuration
- \`prose-config.css\` - @tailwindcss/typography configuration
- \`design-tokens.json\` - Design tokens in JSON format
- \`kitchen-sink.html\` - Example HTML file demonstrating all typography elements
- \`nextjs-install.jsx\` - Next.js installation example
- \`vite-install.html\` - Vite installation example

## See Also

Check out \`kitchen-sink.html\` for a complete example of all typography elements in action.
`.trim()
}

export const generateKitchenSinkHTML = config => {
  const getRoleConfig = role => config[role]?.all || {}
  const getFontFamily = (family, category) => {
    const fallback = category.toLowerCase().includes('serif')
      ? 'serif'
      : 'sans-serif'
    return `"${family}", ${fallback}`
  }

  // Collect all unique fonts with their weights
  const fontMap = new Map()

  // Helper to add font with weight
  const addFont = (family, weight) => {
    if (!family) return
    if (!fontMap.has(family)) {
      fontMap.set(family, new Set())
    }
    fontMap.get(family).add(weight)
  }

  // Add base fonts
  const headingConfig = getRoleConfig('headings')
  const bodyConfig = getRoleConfig('body')
  const uiConfig = getRoleConfig('ui')

  addFont(headingConfig.family, headingConfig.weight)
  addFont(bodyConfig.family, bodyConfig.weight)
  addFont(uiConfig.family, uiConfig.weight)

  // Add element-specific fonts
  Object.values(config.headings || {}).forEach(elemConfig => {
    if (elemConfig?.family) addFont(elemConfig.family, elemConfig.weight)
  })
  Object.values(config.body || {}).forEach(elemConfig => {
    if (elemConfig?.family) addFont(elemConfig.family, elemConfig.weight)
  })
  Object.values(config.ui || {}).forEach(elemConfig => {
    if (elemConfig?.family) addFont(elemConfig.family, elemConfig.weight)
  })

  // Build Google Fonts URL with weights
  const googleFontsUrl = Array.from(fontMap.entries())
    .map(([family, weights]) => {
      const familyName = family.replace(/\s+/g, '+')
      const weightList = Array.from(weights).join(';')
      return `family=${familyName}:wght@${weightList}`
    })
    .join('&')

  // Generate CSS variables inline
  const cssVars = generateCSSExport(config)

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Typography Kitchen Sink</title>
  
  <!-- Tailwind CSS Browser -->
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  
  <!-- Tailwind Typography -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tailwindcss/typography@0.5.x/dist/typography.min.css">
  
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?${googleFontsUrl}&display=swap" rel="stylesheet">
  
  <style>
    /* CSS Variables - Inline for standalone HTML */
${cssVars
  .split('\n')
  .map(line => '    ' + line)
  .join('\n')}
    
      body {
        background: linear-gradient(
          100deg,
          color(xyz 0.274 0.276 1.029) 13.57%,
          color(xyz 0.259 0.245 0.959),
          #1e7ef5,
          #3773ed,
          #4567e6 55.97%,
          #574fd6,
          #6034c7 98.38%
        );
        color: white;
      }
      section {
        background-color: #020618cc;
      }
      header p {
        color: #f3f3f3;
      }
      /* Headings use CSS variables for custom typography */
      h1,
      h2,
      h3,
      h4,
      h5,
      h6 {
        font-family: var(--font-heading);
        font-weight: var(--heading-weight);
        letter-spacing: var(--heading-tracking);
        line-height: var(--heading-leading);
        text-transform: var(--heading-transform);
      }

      section > h2 {
        color: oklch(0.704 0.04 256.788);
      }

      /* Buttons use UI CSS variables for custom typography */
      button {
        font-family: var(--font-ui);
        font-weight: var(--ui-weight);
        letter-spacing: var(--ui-tracking);
        line-height: var(--ui-leading);
        text-transform: var(--ui-transform);
      }
      .prose {
        h1,
        h2,
        h3,
        h4,
        h5,
        h6,
        ul,
        ol,
        td,
        th,
        p,
        em,
        strong,
        code {
          color: #ffffff;
        }
        a {
          color: #93c5fd;
          transition: all 0.3s ease;
          &:hover {
            color: #bfdbfe;
          }
        }
        blockquote {
          border-left-color: #3b82f6;
          color: #d1d5db;
        }
      }
    </style>
</head>
<body class="max-w-5xl mx-auto p-8 text-zinc-200">
  <header class="mb-12">
    <h1 class="text-5xl mb-4">Typography Kitchen Sink</h1>
    <p class="text-lg text-zinc-300">This page demonstrates all typography elements using your configured typography system.</p>
  </header>
  
  <section class="mb-12 p-8 rounded-lg">
    <h2 class="text-2xl mb-6">Headings</h2>
    <div class="space-y-4">
      <h1 class="text-5xl">Heading 1 (H1)</h1>
      <h2 class="text-4xl">Heading 2 (H2)</h2>
      <h3 class="text-3xl">Heading 3 (H3)</h3>
      <h4 class="text-2xl">Heading 4 (H4)</h4>
      <h5 class="text-xl">Heading 5 (H5)</h5>
      <h6 class="text-lg">Heading 6 (H6)</h6>
    </div>
  </section>
  
  <section class="mb-12 p-8 rounded-lg">
    <h2 class="text-2xl mb-6">Body Text</h2>
    <div class="prose prose-invert max-w-none">
      <p>This is a paragraph of body text. It demonstrates the default body typography settings including font family, weight, letter spacing, line height, and text transform.</p>
      <p>Here's another paragraph to show spacing between paragraphs. Notice how the typography system creates a comfortable reading experience with appropriate line height and letter spacing.</p>
    </div>
  </section>
  
  <section class="mb-12 p-8 rounded-lg">
    <h2 class="text-2xl mb-6">Text Formatting</h2>
    <div class="prose prose-invert max-w-none">
      <p>This paragraph contains <strong>strong/bold text</strong> and <em>emphasized/italic text</em> to demonstrate how these elements are styled.</p>
      <p>You can also use <code>inline code</code> within paragraphs, and here's a <a href="#">link to demonstrate link styling</a>.</p>
    </div>
  </section>
  
  <section class="mb-12 p-8 rounded-lg">
    <h2 class="text-2xl mb-6">Blockquote</h2>
    <div class="prose prose-invert max-w-none">
      <blockquote>
        "This is a blockquote. It's used for highlighting important quotes or callouts. Notice how it has distinct styling from regular paragraphs."
      </blockquote>
    </div>
  </section>
  
  <section class="mb-12 p-8 rounded-lg">
    <h2 class="text-2xl mb-6">Lists</h2>
    <div class="prose prose-invert max-w-none">
      <h3>Unordered List</h3>
      <ul>
        <li>First list item</li>
        <li>Second list item with <strong>bold text</strong></li>
        <li>Third list item with <em>italic text</em></li>
        <li>Fourth list item with <code>code</code></li>
      </ul>
      
      <h3>Ordered List</h3>
      <ol>
        <li>First numbered item</li>
        <li>Second numbered item</li>
        <li>Third numbered item</li>
      </ol>
    </div>
  </section>
  
  <section class="mb-12 p-8 rounded-lg">
    <h2 class="text-2xl mb-6">Buttons</h2>
    <div class="flex gap-2">
      <button class="px-4 py-2 bg-blue-600 text-white rounded cursor-pointer hover:bg-blue-700 transition-colors">Primary Button</button>
      <button class="px-4 py-2 bg-green-600 text-white rounded cursor-pointer hover:bg-green-700 transition-colors">Success Button</button>
      <button class="px-4 py-2 bg-red-600 text-white rounded cursor-pointer hover:bg-red-700 transition-colors">Danger Button</button>
    </div>
  </section>
  
  <section class="mb-12 p-8 rounded-lg">
    <h2 class="text-2xl mb-6">Table</h2>
    <div class="prose prose-invert max-w-none overflow-x-auto">
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Heading Font</td>
            <td>Typography</td>
            <td>${headingConfig.family} - ${headingConfig.weight}</td>
          </tr>
          <tr>
            <td>Body Font</td>
            <td>Typography</td>
            <td>${bodyConfig.family} - ${bodyConfig.weight}</td>
          </tr>
          <tr>
            <td>UI Font</td>
            <td>Typography</td>
            <td>${uiConfig.family} - ${uiConfig.weight}</td>
          </tr>
        </tbody>
      </table>
    </div>
  </section>
  
  <section class="mb-12 p-8 rounded-lg">
    <h2 class="text-2xl mb-6">Code Block</h2>
    <div class="prose prose-invert max-w-none">
      <pre><code>// Example code block
function example() {
  const heading = document.querySelector('h1');
  heading.style.fontFamily = 'var(--font-heading)';
  heading.style.fontWeight = 'var(--heading-weight)';
}</code></pre>
    </div>
  </section>
</body>
</html>`
}

export const generateExportZip = async config => {
  // Lazy load JSZip only when export is triggered
  const JSZip = (await import('jszip')).default
  const zip = new JSZip()

  // Create folder structure
  const cssFolder = zip.folder('css')
  const tokensFolder = zip.folder('tokens')
  const styleDictionaryFolder = zip.folder('style-dictionary')
  const examplesFolder = zip.folder('examples')
  const platformsFolder = zip.folder('platforms')

  // CSS files
  cssFolder.file('variables.css', generateCSSExport(config))
  cssFolder.file(
    'tailwind-comprehensive.css',
    generateComprehensiveTailwindConfig(config)
  )
  cssFolder.file('tailwind-basic.css', generateTailwindExport(config))
  cssFolder.file('prose-config.css', generateProseConfig(config))

  // Token files
  tokensFolder.file('design-tokens.json', generateJSONTokens(config))
  tokensFolder.file('tokens.json', generateStyleDictionaryTokens(config))
  tokensFolder.file('w3c-tokens.json', generateW3CTokens(config))
  tokensFolder.file('figma-variables.json', generateFigmaTokens(config))

  // Style Dictionary
  styleDictionaryFolder.file('config.json', generateStyleDictionaryConfig())
  styleDictionaryFolder.file(
    'tokens.json',
    generateStyleDictionaryTokens(config)
  )

  // Platform-specific exports - create nested folders properly
  const iosFolder = platformsFolder.folder('ios')
  iosFolder.file('Typography.swift', generateIOSExport(config))

  const androidFolder = platformsFolder.folder('android')
  androidFolder.file('typography.xml', generateAndroidExport(config))

  const reactNativeFolder = platformsFolder.folder('react-native')
  reactNativeFolder.file('typography.ts', generateReactNativeExport(config))

  const flutterFolder = platformsFolder.folder('flutter')
  flutterFolder.file('typography.dart', generateFlutterExport(config))

  const cssInJSFolder = platformsFolder.folder('css-in-js')
  cssInJSFolder.file('typography.ts', generateCSSInJSExport(config))

  // Examples - create nested folders properly
  const reactExamplesFolder = examplesFolder.folder('react')
  reactExamplesFolder.file(
    'TypographyExamples.tsx',
    generateReactExamples(config)
  )

  const typescriptExamplesFolder = examplesFolder.folder('typescript')
  typescriptExamplesFolder.file(
    'typography.types.ts',
    generateTypeScriptTypes(config)
  )

  const nextjsExamplesFolder = examplesFolder.folder('nextjs')
  nextjsExamplesFolder.file('nextjs-install.jsx', generateNextJSInstall(config))

  const viteExamplesFolder = examplesFolder.folder('vite')
  viteExamplesFolder.file('vite-install.html', generateViteInstall(config))

  const htmlExamplesFolder = examplesFolder.folder('html')
  htmlExamplesFolder.file('kitchen-sink.html', generateKitchenSinkHTML(config))
  htmlExamplesFolder.file('html-install.md', generateHTMLInstall(config))

  // Root level files
  const comprehensiveReadme = `# Typography System Export

This package contains your complete typography system configuration, ready to use across multiple platforms and frameworks.

## 📁 Folder Structure

\`\`\`
.
├── css/                          # CSS files
│   ├── variables.css            # CSS custom properties
│   ├── tailwind-comprehensive.css
│   ├── tailwind-basic.css
│   └── prose-config.css
├── tokens/                       # Design tokens
│   ├── design-tokens.json       # Basic JSON tokens
│   ├── tokens.json              # Style Dictionary format
│   ├── w3c-tokens.json          # W3C Design Tokens format
│   └── figma-variables.json     # Figma Variables format
├── style-dictionary/            # Style Dictionary setup
│   ├── config.json              # Style Dictionary configuration
│   └── tokens.json              # Source tokens
├── platforms/                   # Platform-specific code
│   ├── ios/Typography.swift
│   ├── android/typography.xml
│   ├── react-native/typography.ts
│   ├── flutter/typography.dart
│   └── css-in-js/typography.ts
└── examples/                    # Usage examples
    ├── react/TypographyExamples.tsx
    ├── typescript/typography.types.ts
    ├── nextjs/nextjs-install.jsx
    ├── vite/vite-install.html
    └── html/
        ├── kitchen-sink.html
        └── html-install.md
\`\`\`

## 🚀 Quick Start

### Web (CSS Variables)

1. Link \`css/variables.css\` in your HTML:
   \`\`\`html
   <link rel="stylesheet" href="css/variables.css">
   \`\`\`

2. Use in your CSS:
   \`\`\`css
   .heading {
     font-family: var(--font-heading);
     font-weight: var(--heading-weight);
   }
   \`\`\`

### Tailwind CSS

1. Copy \`css/tailwind-comprehensive.css\` to your project
2. Import it in your main CSS file
3. Use utility classes: \`text-heading-xl\`, \`text-body-base\`, etc.

### Style Dictionary

1. Install Style Dictionary:
   \`\`\`bash
   npm install style-dictionary
   \`\`\`

2. Copy the \`style-dictionary/\` folder to your project
3. Run Style Dictionary:
   \`\`\`bash
   npx style-dictionary build
   \`\`\`

This will generate platform-specific code in the \`build/\` directory.

### Figma

1. Use the \`tokens/figma-variables.json\` file
2. Import via Figma Variables API or Tokens Studio plugin
3. Or use \`tokens/w3c-tokens.json\` with compatible Figma plugins

### React / Next.js

See \`examples/react/TypographyExamples.tsx\` for React component examples.
See \`examples/nextjs/nextjs-install.jsx\` for Next.js font setup.

### Mobile Platforms

- **iOS**: Use \`platforms/ios/Typography.swift\` in your SwiftUI project
- **Android**: Use \`platforms/android/typography.xml\` in your Android project
- **React Native**: Import \`platforms/react-native/typography.ts\`
- **Flutter**: Import \`platforms/flutter/typography.dart\`

## 📚 Documentation

### CSS Variables

All typography settings are available as CSS custom properties:

- \`--font-heading\`, \`--font-body\`, \`--font-ui\`
- \`--heading-weight\`, \`--body-weight\`, \`--ui-weight\`
- \`--heading-tracking\`, \`--body-tracking\`, \`--ui-tracking\`
- \`--heading-leading\`, \`--body-leading\`, \`--ui-leading\`
- \`--heading-transform\`, \`--body-transform\`, \`--ui-transform\`

### Design Tokens

The \`tokens/\` folder contains design tokens in multiple formats:

- **design-tokens.json**: Simple JSON format
- **tokens.json**: Style Dictionary format (with \`$type\` annotations)
- **w3c-tokens.json**: W3C Design Tokens standard format
- **figma-variables.json**: Figma Variables API format

### TypeScript Support

Type definitions are available in \`examples/typescript/typography.types.ts\`.

## 🎨 Examples

Check the \`examples/\` folder for:

- **React**: Component examples with TypeScript types
- **TypeScript**: Type definitions for typography system
- **Next.js**: Installation guide for Next.js projects
- **Vite**: Setup instructions for Vite projects
- **HTML**: Kitchen sink demo and HTML installation guide

## 🔧 Customization

All files are generated from your typography configuration. To regenerate:

1. Use TypePalette to adjust your typography settings
2. Export again to get updated files

## 📖 Additional Resources

- [Style Dictionary Documentation](https://amzn.github.io/style-dictionary/)
- [W3C Design Tokens Specification](https://tr.designtokens.org/format/)
- [Figma Variables API](https://www.figma.com/developers/api#variables)
- [Tailwind CSS Typography Plugin](https://tailwindcss.com/docs/plugins#typography)

## 🤝 Support

For issues or questions, visit the TypePalette repository.

---

Generated by [TypePalette](https://github.com/yourusername/typepalette)
`

  // Root level files
  zip.file('README.md', comprehensiveReadme)
  zip.file('kitchen-sink.html', generateKitchenSinkHTML(config))

  // Generate zip file and trigger download
  const blob = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = 'typography-export.zip'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
